###
# @CreateProduct
POST http://localhost:7000/api/v1/products/
Content-Type: application/json

{
      "productCode": "MCC9988",
      "price": 2000,
      "name": "MacBook Pro"
      
}

###
# @CreateProduct
POST http://localhost:6000/api/v1/products/
Content-Type: application/json

{
      "productCode": "MCG002",
      "price": 1000,
      "name": "Theme Templates"
      
}

###
# @Create an Inventory
POST  http://localhost:7000/api/v1/inventory/
Content-Type: application/json

[
    {
        "productCode": "MCC9988",
        "quantity": 100
    },
    {
        "productCode": "MCG002",
        "quantity": 50
    }
]


###
# @Place order
POST http://localhost:7000/api/v1/orders/
Content-Type: application/json

{
  "orderItems": [
    {
      "productCode": "MCG002",
      "quantity": 45
    },
    {
      "productCode": "MCC9988",
      "quantity": 98
    }
  ]
}

###
# @Make Order payment
POST http://localhost:7000/api/v1/payments/process?orderId=ORD-78aadb06-4a33-40fe-81dc-90df7fd843dd-0
Content-Type: application/json

    {
      "orderId": "ORD-e8294c1a-c801-4baf-8805-f07c4757a4d0-0",
      "paymentMethod": "MOBILE_MONEY",
      "paymentProvider": "M-PESA",
      "amount": 147000.00
    }


###
# @AllOrder
GET  http://localhost:7000/api/v1/orders/
Content-Type: application/json

###
# @AllOrder between two dates
GET  http://localhost:7000/api/v1/orders/filter?startDate=2024-03-20&endDate=2024-03-22
Content-Type: application/json

###
# @AllOrder before a certain date
GET  http://localhost:7000/api/v1/orders/filter?endDate=2024-03-25
Content-Type: application/json

###
# @AllOrder after a certain date
GET  http://localhost:7000/api/v1/orders/filter?startDate=2024-03-24
Content-Type: application/json

###
# @AllOrder after a certain date // returns an error..one value must be present
GET  http://localhost:7000/api/v1/orders/
Content-Type: application/json



###
# @Create an Inventory
POST  http://localhost:7000/api/v1/inventory/
Content-Type: application/json

[
  { "productCode": "DELL-100", "quantity": 1000 },
  { "productCode": "HP-100", "quantity": 1000 },
  { "productCode": "GPX-100", "quantity": 1000 },
  { "productCode": "SLW-100", "quantity": 1000 },
  { "productCode": "SLW-200", "quantity": 500 },
  { "productCode": "SLW-300", "quantity": 700 },
  { "productCode": "SLW-108", "quantity": 1200 },
  { "productCode": "SLW-110", "quantity": 1900 }
]

### Add single inventory
POST  http://localhost:7000/api/v1/inventory/
Content-Type: application/json

[
  { "productCode": "SLW-109", "quantity": 1200 }
]


### @AllInventory
GET  http://localhost:6002/api/v1/inventory/
Content-Type: application/json
### @AllInventory
GET  http://localhost:7000/api/v1/payments/
Content-Type: application/json


### @AllInventory
GET  http://localhost:6000/swagger-ui.html
Content-Type: application/json


###
# @Delete Inventory BY Id
DELETE  http://localhost:7000/api/v1/inventory/delete/660164327865676373707723
Content-Type: application/json


###
# @Place order
POST http://localhost:7000/api/v1/orders/
Content-Type: application/json

{
  "orderItems": [
    {
      "productCode": "DELL-100",
      "quantity": 5
    },
    {
      "productCode": "HP-100",
      "quantity": 6
    },
    {
      "productCode": "GPX-100",
      "quantity": 5
    },
    {
      "productCode": "SLW-200",
      "quantity": 3
    },
    {
      "productCode": "SLW-300",
      "quantity": 5
    }
  ]
}

