###
# @CreateProduct
POST http://localhost:7000/api/v1/products/
Content-Type: application/json

{
      "productCode": "MCC9988",
      "price": 2000,
      "name": "MacBook Pro"
      
}

###
# @AllOrder
GET  http://localhost:7000/api/v1/orders/
Content-Type: application/json

###
# @AllOrder between two dates
GET  http://localhost:7000/api/v1/orders/filter?startDate=2024-03-20&endDate=2024-03-22
Content-Type: application/json

###
# @AllOrder before a certain date
GET  http://localhost:7000/api/v1/orders/filter?endDate=2024-03-22
Content-Type: application/json

###
# @AllOrder after a certain date
GET  http://localhost:7000/api/v1/orders/filter?startDate=2024-03-20
Content-Type: application/json

###
# @AllOrder after a certain date // returns an error..one value must be present
GET  http://localhost:7000/api/v1/orders/filter
Content-Type: application/json


###
# @Create an Inventory
POST  http://localhost:7000/api/v1/inventory/
Content-Type: application/json

{
  "productCode": "MCG002",
  "quantity": -12
}


###
# @AllInventory
GET  http://localhost:7000/api/v1/inventory/
Content-Type: application/json


###
# @Delete Inventory BY Id
DELETE  http://localhost:7000/api/v1/inventory/delete/660022591f43f32d49890ff4
Content-Type: application/json


###
# @Place order
POST http://localhost:7000/api/v1/orders/
Content-Type: application/json

{
  "orderItems": [
    {
      "productCode": "MCC002",
      "quantity": 20
    },
    {
      "productCode": "MCA002",
      "quantity": 20
    }
  ]
}