server:
  port: 7000
spring:  
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**  

        - id: orders
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/** 

        - id: inventory
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/** 

  application:
    name: api-gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka