server:
  port: 8761
  tomcat:
    accept-count: ${SERVER_TOMCAT_ACCEPT_COUNT:10}
    max-connections: ${SERVER_TOMCAT_MAX_CONNECTIONS:10}
    threads:
      max: ${SERVER_TOMCAT_THREADS_MAX:3}
      min-spare: ${SERVER_TOMCAT_THREADS_MIN_SPARE:1}

java:
  tool-options: ${JAVA_TOOL_OPTIONS:"-XX:+UseSerialGC -Xss512k -XX:MaxRAM=200m"}

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    