server:
  port: 6001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordersdb
    username: root
    password: root
  appliction:
    name: order-service
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: create-drop
