server:
  port: 6001
  tomcat:
    accept-count: ${SERVER_TOMCAT_ACCEPT_COUNT:3}
    max-connections: ${SERVER_TOMCAT_MAX_CONNECTIONS:3}
    threads:
      max: ${SERVER_TOMCAT_THREADS_MAX:3}
      min-spare: ${SERVER_TOMCAT_THREADS_MIN_SPARE:1}

java:
  tool-options: ${JAVA_TOOL_OPTIONS:"-XX:+UseSerialGC -Xss512k -XX:MaxRAM=150m"}

spring:
  profiles:
    active: development, default
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: order-service

payment:
  process-url: /api/v1/payments/process?orderId=

openapi:
  service:
    title: Orders-service RestApiDocs
    version: 1.0.0
    url: http://localhost:7000

springdoc:
  api-docs:
    path: /orders/v3/api-docs
  swagger-ui:
    path: /orders/swagger-ui.html
    operationsSorter: method
