server:
  port: 6001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordersdb
    username: root
    password: root
  application:
    name: order-service
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: update

eureka:
  # instance:
  #   hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka