server:
  port: 6001
spring:
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5433/ordersdb
    username: postgres
    password: generic
  application:
    name: order-service
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: create-drop    