server:
  port: 6001
spring:
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/ordersdb
    username: root
    password: root
  application:
    name: order-service
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: update
