server:
  port: 6000
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/productsdb
    username: root
    password: root
  config:
    import: optional:configserver:http://localhost:8888
    
  application:
    name: product-service
    
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: update