server:
  port: 6002
spring:
  data:
    mongodb: 
        # uri: mongodb://root:generic@localhost:27017/inventorydb?authSource=admin
        host: localhost
        port: 27017
        username: root
        password: generic
        authentication-database: admin
        database: inventorydb
        
  application:
    name: inventory-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka